FROM node:18-alpine AS builder
WORKDIR /app

COPY src ./src

RUN mkdir -p public && cp -R src/* public/

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/public /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
