services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pokefy
      POSTGRES_PASSWORD: pokepass
      POSTGRES_DB: pokefav
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://pokefy:pokepass@db:5432/pokefav
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db-data: